-- ----------------------------------------------------------------------------------
-- SCRIPT DE PROVISIONAMENTO PARA TESTES DE INTEGRAÇÃO (PROFILE: TEST)
-- Banco de Dados: H2 em memória (compatível também com PostgreSQL)
-- Objetivo: garantir schema mínimo + dados base de Artista para testes idempotentes
-- ----------------------------------------------------------------------------------

-- 0. DROP de segurança (caso o Hibernate ou execuções anteriores já tenham criado)
DROP TABLE IF EXISTS TB_OBR_ART;
DROP TABLE IF EXISTS TB_ARTST;

-- 1. CRIAÇÃO DO SCHEMA MÍNIMO
-- Espelhando as entidades ArtistaPostgres_DomainModel e ObraArtePostgres_DomainModel

CREATE TABLE TB_ARTST (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo    VARCHAR(150) NOT NULL,
    email            VARCHAR(150) NOT NULL UNIQUE,
    username         VARCHAR(100) NOT NULL UNIQUE,
    senha            VARCHAR(255) NOT NULL,
    biografia        TEXT,
    data_registro    TIMESTAMP NOT NULL
);

CREATE TABLE TB_OBR_ART (
    id_obra_arte      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo            VARCHAR(200) NOT NULL,
    descricao         TEXT,
    ano_criacao       INT NOT NULL,
    tecnica_utilizada VARCHAR(100) NOT NULL,
    artista_id        BIGINT NOT NULL,
    CONSTRAINT fk_obra_artista
        FOREIGN KEY (artista_id) REFERENCES TB_ARTST(id)
);

-- 2. LIMPEZA TOTAL (CLEANUP)
DELETE FROM TB_OBR_ART;
DELETE FROM TB_ARTST;

-- 3. INSERÇÃO DE DADOS BASE (Artista mockado para testes)
INSERT INTO TB_ARTST (
    id, nome_completo, email, username, senha, biografia, data_registro
) VALUES (
    99,
    'Michelangelo de Teste',
    'micha@teste.com',
    'micha_teste',
    '$2a$10$HASHED_PASS_MOCK',
    'Artista renascentista mockado para testes.',
    NOW() -- H2 entende NOW(); pode trocar por CURRENT_TIMESTAMP se preferir
);
